// Copyright (C) 2020 - Directive Games Limited - All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "HAL/LowLevelMemStats.h"


DECLARE_STATS_GROUP(TEXT("glTFRuntime"), STATGROUP_glTFRuntime, STATCAT_Advanced);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Material"), STAT_LoadMaterial, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Texture"), STAT_LoadTexture, STATGROUP_glTFRuntime, GLTFRUNTIME_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("From Data"), STAT_FromData, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("From Filename"), STAT_FromFilename, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("From String"), STAT_FromString, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("From Binary"), STAT_FromBinary, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Scene"), STAT_LoadScene, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Primitives"), STAT_LoadPrimitives, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Primitive"), STAT_LoadPrimitive, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("BuildFromAccessorField"), STAT_BuildFromAccessorField, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("GetAccessor"), STAT_GetAccessor, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("GetBufferView"), STAT_GetBufferView, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("GetBuffer"), STAT_GetBuffer, STATGROUP_glTFRuntime, GLTFRUNTIME_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Skeletal Mesh"), STAT_LoadSkeletalMesh, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Create Skeletal Mesh From LODs"), STAT_CreateSkeletalMeshFromLODs, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Finalize Skeletal Mesh With LODs"), STAT_FinalizeSkeletalMeshWithLODs, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Build Skeletal Mesh"), STAT_BuildSkeletalMesh, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Save LOD Imported Data"), STAT_SaveLODImportedData, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("USkeletalMesh::Build"), STAT_SkeletalMeshBuild, STATGROUP_glTFRuntime, GLTFRUNTIME_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Static Mesh"), STAT_LoadStaticMesh, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Build Texture"), STAT_BuildTexture, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Build Material"), STAT_BuildMaterial, STATGROUP_glTFRuntime, GLTFRUNTIME_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("glTF Begin Play"), STAT_BeginPlay, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Node"), STAT_LoadNode, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Process Node"), STAT_ProcessNode, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Add Static Mesh Component"), STAT_AddStaticMeshComponent, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Add Skeletal Mesh Component"), STAT_AddSkeletalMeshComponent, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Add Camera Component"), STAT_AddCameraComponent, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Add Scene Component"), STAT_AddSceneMeshComponent, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Animation Curves"), STAT_LoadAnimationCurves, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Load Skeletal Animation"), STAT_LoadSkeletalAnimation, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("LoadAnimation_Internal"), STAT_LoadAnimation_Internal, STATGROUP_glTFRuntime, GLTFRUNTIME_API);

#if ENABLE_LOW_LEVEL_MEM_TRACKER
enum class EglTFRuntimeLLMTag : LLM_TAG_TYPE
{
	LoadAssets = (uint32)ELLMTag::ProjectTagStart + 10,
	LoadStaticMesh,
	LoadSkeletalMesh,
	FinalizeSkeletalMesh,
	LoadMaterial,
	LoadTexture,
	LoadPrimitives,
	LoadAnimation,
	LoadMorphTarget,
	InitMorphTarget,
	BuildTexture,
	BuildMaterial,
	LoadJson,
	StoreBinaryBuffer,
};

DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Assets"), STAT_LoadAssetsLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Static Mesh"), STAT_LoadStaticMeshLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Skeletal Mesh"), STAT_LoadSkeletalMeshLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Finalize Skeletal Mesh"), STAT_FinalizeSkeletalMeshLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Material"), STAT_LoadMaterialLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Texture"), STAT_LoadTextureLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Primitives"), STAT_LoadPrimitivesLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Animation"), STAT_LoadAnimationLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Morph Target"), STAT_LoadMorphTargetLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Init Morph Target"), STAT_InitMorphTargetLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Build Texture"), STAT_BuildTextureLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Build Material"), STAT_BuildMaterialLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Load Json"), STAT_LoadJsonLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
DECLARE_LLM_MEMORY_STAT_EXTERN(TEXT("glTF Store Binary Buffer"), STAT_StoreBinaryBufferLLM, STATGROUP_glTFRuntime, GLTFRUNTIME_API);
#endif
